plugins {
    id 'com.android.application'
}

android {
    namespace 'app.rivaya.next'
    compileSdk 35

    defaultConfig {
        applicationId "app.rivaya.next"
        minSdk 26
        targetSdk 35
        versionCode 1
        versionName "3.0.0-new"
    }

    buildTypes {
        debug {
            minifyEnabled false
        }
        release {
            minifyEnabled false
        }
    }
}

dependencies {
}
