plugins {
    id 'com.android.application'
}

android {
    namespace 'app.rivaya.next'
    compileSdk 35

    defaultConfig {
        applicationId "app.rivaya.smart01"
        minSdk 26
        targetSdk 35
        versionCode 30100
        versionName "3.1.0-premium"
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    buildTypes {
        debug {
            minifyEnabled false
        }
        release {
            minifyEnabled false
        }
    }
}

dependencies {
    androidTestImplementation 'androidx.test:runner:1.6.2'
    androidTestImplementation 'androidx.test:rules:1.6.1'
    androidTestImplementation 'androidx.test.ext:junit:1.2.1'
    androidTestImplementation 'androidx.test.uiautomator:uiautomator:2.3.0'
}
